---
#- hosts: compute-server
#- hosts: fstgb013,fstgb014,fstgb015
#- hosts: fnode3-6
#- hosts: bnode6-3
- hosts: fnode6-7
#- hosts: svf12
  remote_user: root
  gather_facts: true
  vars :
    - toolsdir : /usr/lib/python2.7/dist-packages/nova/compute/
  tasks:

    - name : copy gpu_states.py
      copy: src=gpu_states.py  dest={{toolsdir}}  owner=root group=root mode=0644
      when: ansible_os_family =="Debian"

    - name : copy capi_states.py
      copy: src=capi_states.py  dest={{toolsdir}}  owner=root group=root mode=0644
      when: ansible_os_family =="Debian"

    - name : copy sdaccel_states.py
      copy: src=sdaccel_states.py  dest={{toolsdir}}  owner=root group=root mode=0644
      when: ansible_os_family =="Debian"
