---
- hosts: compute,controller
 
  remote_user: root
  gather_facts: true
  vars :
    - toolsdir : /root
  tasks:

    - name : copy tools bakcompute.sh
      copy: src=openstackfile/bakcompute.sh  dest={{toolsdir}}  owner=root group=root mode=0755

    - name : copy tools getcomputevm.sh
      copy: src=openstackfile/getcomputevm.sh  dest={{toolsdir}}  owner=root group=root mode=0755

    - name : copy tools cpservice_act.sh
      copy: src=openstackfile/cpservice_act.sh  dest={{toolsdir}}  owner=root group=root mode=0755
      when : ansible_os_family =="RedHat" 
      #when : ansible_os_family =="CentOS"

    - name : copy tools bashrc.centos7.2
      copy: src=openstackfile/bashrc.centos7.2  dest={{toolsdir}}/.bashrc  owner=root group=root mode=0644
      #when : ansible_os_family =="CentOS"
      when : ansible_os_family =="RedHat" 

    - name : copy tools p8servicerestart.sh
      copy: src=openstackfile/p8servicerestart.sh  dest={{toolsdir}}  owner=root group=root mode=0755
      when: ansible_os_family =="Debian"


    - name : copy tools bashrc.16.04.1
      copy: src=openstackfile/bashrc.16.04.1 dest={{toolsdir}}/.bashrc  owner=root group=root mode=0644
      when: ansible_os_family =="Debian"
