- hosts: ent-op-server
  vars:
    filepath : /etc/ssh/ssh_config
    options : StrictHostKeyChecking
  remote_user: root
  tasks:
    - name: Config {{filepath}}
      lineinfile: dest={{filepath}} state=present regexp='^{{options}}' line='{{item}}'
      with_items:
        - "{{ options}} no"
          #- "Defaults: {{user}}  !requiretty"

