#- hosts: ent-op-server
- hosts: op-server
  remote_user: root
  gather_facts: no
  vars:
    filepath : /etc/ssh/ssh_config
    options : StrictHostKeyChecking
  tasks:
    - name: Config {{filepath}}
      lineinfile: dest={{filepath}} state=present regexp='^{{options}}' line='{{item}}'
      with_items:
        - "{{ options}} no"
          #- "Defaults: {{user}}  !requiretty"

