- hosts: ent-op-server
  vars:
    user: opadmin
    # xxxx
    password2: "$6$rounds=40000$3mBJ1KoxU7KPgmqx$Q/92Y64H/.sPuH9J3VAJxu5K5htaZK3ejOHMlPb5.tNPQJuD21BDgAKhvp2Q1/1qw1jGksOp0uhvZup0kO6gW1"
    remote_user: root
  tasks:
    - name: Add user {{ user }}
      user: name={{user}} shell=/bin/bash password={{ password2 }}

    - name: Config /etc/sudoers
      lineinfile: dest=/etc/sudoers state=present regexp='^Cmnd_Alias' line='{{item}}' validate='visudo -cf %s'
      with_items:
        #- "Cmnd_Alias SQUID =  /usr/sbin/service, /bin/rm, /bin/ls, /sbin/initctl , /sbin/reboot, /sbin/shutdown"
        - "Cmnd_Alias SQUID =  /usr/sbin/service, /bin/rm, /sbin/initctl , /sbin/reboot, /sbin/shutdown"

    - name: Config /etc/sudoers
      lineinfile: dest=/etc/sudoers state=present regexp='^{{user}}' line='{{item}}' validate='visudo -cf %s'
      with_items:
        - "{{ user}} ALL=(ALL) NOPASSWD: SQUID"
          #- "Defaults: {{user}}  !requiretty"

