---
#- hosts: compute-server
- hosts: compute-server-ubuntu-chuanghe,compute-server-ubuntu-p8
  remote_user: root
  gather_facts: no
  vars:
    user: testuser
    # xxxxx
    #password2: "$6$rounds=40000$3mBJ1KoxU7KPgmqx$Q/92Y64H/.sPuH9J3VAJxu5K5htaZK3ejOHMlPb5.tNPQJuD21BDgAKhvp2Q1/1qw1jGksOp0uhvZup0kO6gW1"
    password: "$6$rounds=40000$t/DWJ/817RthjXSt$y7Wf0L6S3zG.FdvelFtx03jBOc.FblgYoZXNhG/tUdBhdz4XRccR/rxojlk3Tj7vNNAGuLuiMiT3vmcfh3ssR1"

  remote_user: root
  tasks:
    - name: Add user {{ user }}
      user: name={{user}} shell=/bin/bash password={{ password }} remove=yes state=absent

