---
- hosts: compute-server
#- hosts: svf12
  remote_user: root
  gather_facts: true
  vars :
    - toolsdir : /root
  tasks:

    - name : copy tools bakcompute.sh
      copy: src=openstackfile/bakcompute.sh  dest={{toolsdir}}  owner=root group=root mode=0755

    - name : copy tools getcomputevm.sh
      copy: src=openstackfile/getcomputevm.sh  dest={{toolsdir}}  owner=root group=root mode=0755

    - name : copy tools cpservice_act.sh
      copy: src=openstackfile/cpservice_act.sh  dest={{toolsdir}}  owner=root group=root mode=0755
      when : ansible_os_family =="RedHat" 
      #when : ansible_os_family =="CentOS"


    - name : copy tools p8servicerestart.sh
      copy: src=openstackfile/p8servicerestart.sh  dest={{toolsdir}}  owner=root group=root mode=0755
      when: ansible_os_family =="Debian"
