---
#- hosts: compute-server
#- hosts: cp9,cp12,cp13,chuanghe1,chuanghe2,chuanghe3,cp8
- hosts: redpower5,cp17,cp9
  remote_user: root
  gather_facts: no
  remote_user: root
  vars :
    - monitordir : /home/linzhbj/servicemonitor
  tasks:
    - name : create log dir
      file : name={{monitordir}}/curlog state=directory

#    - name : delete old crontab for service check
#      shell : crontab -l  | grep -v "/home/linzhbj/servicecheck.sh"  | crontab

#    - name : delete old crontab for killpid check
#      shell : crontab -l  | grep -v "/home/linzhbj/clearwork/killpid.sh"  | crontab

    - name : copy monitor script
      copy: src=openstackfile/servicecheck.sh  dest={{monitordir}}  owner=root group=root mode=0755

    - name : config crontab
      cron : name="Monitor nova-compute & neutron-openvswitch-agent" minute=0 hour=*/1
             job="{{monitordir}}/servicecheck.sh >> {{monitordir}}/curlog/servicecheck.log 2>>{{monitordir}}/curlog/servicecheck.log.err"


    - name : config client service monitor
      copy : src=openstackfile/crontab_servicemoitor.sh dest={{monitordir}} owner=root group=root mode=0755
      tags : tag_copy

    - name : copy novainfo.py 
      copy : src=openstackfile/novainfo.py dest={{monitordir}} owner=root group=root mode=0755
      tags : tag_copy

    - name : copy performanceMonitor.py
      copy : src=openstackfile/performanceMonitor.py dest={{monitordir}} owner=root group=root mode=0755
      tags : tag_copy


#    - name : delete old crontab for service monitor
#      shell : crontab -l  | grep -v "/home/linzhbj/servicemonitor/crontab_servicemoitor.sh"  | crontab

    - name : config crontab nova & nutron client api monitor
      cron : name="Monitor client api  nova-compute & neutron-openvswitch-agent" minute=30 hour=*/1
             job="{{monitordir}}/crontab_servicemoitor.sh >> {{monitordir}}/curlog/servicemoitor.log 2>>{{monitordir}}/curlog/servicemoitor.log.err"
