---
- hosts: ansible
  remote_user: root
  gather_facts: true
  tasks:
  - debug:
      #msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
      msg: "hostname {{ inventory_hostname }}"
