---
- hosts : controller-server
  remote_user: root
  gather_facts: no
  tasks :
    - name: start mariadb service
      service: name=mariadb state=stopped  enabled=no

    - name : copy server.conf
      copy : src=my.cnf.d/server.cnf dest=/etc/my.cnf.d/server.cnf   owner=root group=root mode=0644
