---
- hosts : controller-server
  remote_user: root
  gather_facts: no
  tasks :
    - name: start mariadb service
      service: name=mariadb state=stopped  enabled=no

#    - name : copy haproxy.cfg
#      copy : src=haproxy.cfg  dest=/etc/haproxy/haproxy.cfg   owner=root group=root mode=0644
