---
- hosts : controller-server
  remote_user: root
  gather_facts: no
  tasks :
    - name: start pcs service
      service: name=pcsd state=started  enabled=yes

    - name : copy haproxy.cfg
      copy : src=haproxy.cfg  dest=/etc/haproxy/haproxy.cfg   owner=root group=root mode=0644
