---
#- hosts: compute-server
#- hosts: fstgb013,fstgb014,fstgb015
#- hosts: fnode3-6
- hosts: bnode6-3
  remote_user: root
  gather_facts: true
  vars :
    - toolsdir : /etc/nova/rootwrap.d/
  tasks:

    - name : copy docker.filters
      copy: src=docker.filters  dest={{toolsdir}}  owner=nova group=nova mode=0644
      when: ansible_os_family =="Debian"

#    - name: Config /etc/nova/nova.conf
#      lineinfile: dest=/etc/nova/nova.conf state=present regexp='^compute_driver=' line='compute_driver=novadocker.virt.docker.DockerDriver'
#
#    - name: Config /etc/nova/nova-compute.conf
#      lineinfile: dest=/etc/nova/nova-compute.conf state=present regexp='^compute_driver=' line='compute_driver=novadocker.virt.docker.DockerDriver'

    - name : docker group
      shell : usermod -a -G docker nova
    
    - name : service nova-compute
      service : name=nova-compute state=restarted enabled=yes

    - name : serviceneutron-openvswitch-agent 
      service : name=neutron-openvswitch-agent state=restarted enabled=yes
