---
- hosts : m-ctl-server
  remote_user: root
  gather_facts: no
  tasks :
  - name : ping
    ping :

  - name: Config /etc/nova/nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: conductor
      option: workers
      value: 4

  - name: Config /etc/nova/nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: DEFAULT
      option: osapi_compute_workers
      value: 4

  - name: Config /etc/nova/nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: DEFAULT
      option: metadata_workers
      value: 4


  - name: Config /etc/glance/glance-api.conf
    ini_file: 
      dest: /etc/glance/glance-api.conf
      section: DEFAULT
      option: debug
      #value: True
      value: False

  - name: Config /etc/glance/glance-api.conf
    ini_file: 
      dest: /etc/glance/glance-api.conf
      section: DEFAULT
      option: workers
      value: 4

  - name: Config /etc/glance/glance-api.conf
    ini_file: 
      dest: /etc/glance/glance-api.conf
      section: DEFAULT
      option: auth_strategy
      value: keystone

  - name: Config /etc/glance/glance-registry.conf
    ini_file: 
      dest: /etc/glance/glance-registry.conf
      section: DEFAULT
      option: workers
      value: 4
