heat_template_version: 2015-10-15
description: Launch a basic instance with CirrOS image using the
             ``m1.tiny`` flavor, ``mykey`` key,  and one network.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.
    default: 0dc977d0-90ce-4055-aac4-cb4ee21bc461

  image:
    type: string
    description: Image used for servers
    default: ubuntu_14_lts_docker_aufs_ppc64le_v0.1.0

  flavor:
    type: string
    description: flavor used by the servers
    default: docker.small

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      networks:
      - network: { get_param: NetID }

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server, first_address ] }

