---
- hosts : ctl-n1, ctl-n2, ctl-n3
  remote_user: root
  gather_facts: no
  tasks :
  - name: Config nova.conf
    ini_file:
      dest: /etc/nova/nova.conf
      section: oslo_middleware
      option: max_request_body_size
      value : 229376
      #value : 114688
