---
#- hosts : install-server
- hosts : compute-server-ppc64le-docker
  remote_user: root
  gather_facts: no
  tasks :
  - name: Config nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: DEFAULT
      option: compute_driver
      value: novadocker.virt.docker.DockerDriver 
      #value : libvirt.LibvirtDriver

  - name: Config nova-compute.conf
    ini_file: 
      dest: /etc/nova/nova-compute.conf
      section: DEFAULT
      option: compute_driver
      value: novadocker.virt.docker.DockerDriver 
      #value : libvirt.LibvirtDriver
 
  - name: Config nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: docker 
      option: cpu_capping
      value: true
      #value : libvirt.LibvirtDriver
 
  - name: Config nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: docker 
      option: set_fs_size
      value: true
 
  - name: Config nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: docker 
      option: client_timeout
      value: 3600

  - name: Config nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: docker 
      option: network_device_mtu
      value: 1450

  - name: Config nova.conf
    ini_file:
      dest: /etc/nova/nova.conf
      section: docker
      option: ssh_key_bind_path
      value: /var/lib/nova/instances

  - name: Config nova.conf
    ini_file:
      dest: /etc/nova/nova.conf
      section: docker
      option: metadata_storage_dir
      value: /var/lib/nova/metadata

  - name : service nova-compute
    service : name=nova-compute state=restarted enabled=yes

  - name : service neutron-openvswitch-agent
    service : name=neutron-openvswitch-agent state=restarted enabled=yes
