---
- hosts : compute-server-ppc64le-kvm
  remote_user: root
  gather_facts: no
  tasks :
  - name: Config nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: DEFAULT
      option: compute_driver
      value : libvirt.LibvirtDriver

  - name: Config nova.conf
    ini_file: 
      dest: /etc/nova/nova.conf
      section: DEFAULT
      option: resume_guests_state_on_host_boot
      value: True


