---
- hosts : install-server
  gather_facts: no
  tasks :
#  - name : nova.conf 
#    copy: src=nova.conf  dest=/etc/nova/nova.conf  owner=nova group=nova mode=0644
#
#  - name : neutron.conf
#    copy: src=neutron.conf  dest=/etc/neutron/neutron.conf  owner=neutron group=neutron mode=0644
#
#  - name : openvswitch_agent.ini
#    copy: src=openvswitch_agent.ini  dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini  owner=neutron group=neutron mode=0644


#  - name : update nova compute
#    #shell: MYIP=$(grep `hostname` /etc/hosts | grep '192.168' | awk -F  ' ' '{print $1}');sed -i 's/^my_ip.\+/my_ip=${MYIP}/g' /etc/nova/nova.conf
#    shell: MYIP=$(grep `hostname` /etc/hosts | grep "192.168.128." | awk -F  " " '{print $1}');sed -i "s/^my_ip.\+/my_ip=${MYIP}/g" /etc/nova/nova.conf;grep '^my_ip' /etc/nova/nova.conf

  - name : update nova openvswitch_agent.ini
    shell: LOCALIP=$(grep `hostname` /etc/hosts | grep "10.10" | awk -F  ' ' '{print $1}');sed -i "s/^local_ip.\+/local_ip=${LOCALIP}/g" /etc/neutron/plugins/ml2/openvswitch_agent.ini 

  - name : check local_ip
    shell : grep  -nr "^local_ip" /etc/neutron/plugins/ml2/openvswitch_agent.ini
