---
- hosts: compute-server-docker

  remote_user: root
  gather_facts: false
  vars :
    - toolsdir : /opt/computeTEM
  tasks:

    - name : create computeTEM  dir
      file : name={{toolsdir}} state=directory

    - name : copy tools autoinstallTEM.inhost.sh
      copy: src=autoinstallTEM.inhost.sh  dest={{toolsdir}}  owner=root group=root mode=0755

    - name : copy tools autoInstallTem.sh
      copy: src=autoInstallTem.sh  dest={{toolsdir}}  owner=root group=root mode=0755

    - name : copy tools autoStartTem.sh
      copy: src=autoStartTem.sh  dest={{toolsdir}}  owner=root group=root mode=0755

    - name : copy tools autoStopTem.sh
      copy: src=autoStopTem.sh  dest={{toolsdir}}  owner=root group=root mode=0755

#    - name : copy tools cpservice_act.sh
#      copy: src=openstackfile/cpservice_act.sh  dest={{toolsdir}}  owner=root group=root mode=0755
#      when : ansible_os_family =="RedHat"
#      #when : ansible_os_family =="CentOS"


#    - name : copy tools p8servicerestart.sh
#      copy: src=openstackfile/p8servicerestart.sh  dest={{toolsdir}}  owner=root group=root mode=0755
#      when: ansible_os_family =="Debian"
