#- hosts: svx06,svx07,svx08
- hosts: svx12,svx13,svx14
#- hosts: svx07
  remote_user : root
  gather_facts: True
  tasks:

    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        file : epel
        baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        proxy : http://9.115.78.100:8085
        enabled : yes
        gpgcheck: no

    - name: Add  rdo repository
      yum_repository:
        name: RDO-mitaka 
        description: RDO-mitaka 
        baseurl: http://centos.ustc.edu.cn/centos/7.2.1511/cloud/x86_64/openstack-mitaka/
        file : rdo-mitaka 
        proxy : http://9.115.78.100:8085
        enabled : yes
        gpgcheck: no



#    - name : install vim tree
#      yum : name=vim,tree state=latest

    - name : install nova-compute neutron agent
      #yum : name=openstack-nova-compute,openstack-neutron-openvswitch,telnet,ipset state=latest
      yum : name=openstack-nova-compute,openstack-neutron-openvswitch,openstack-neutron,telnet,ipset state=latest

#    - name : install ceph-common
#      yum : name=ceph-common state=latest

    - name : enable openvswitch
      service : name=openvswitch state=started enabled=yes
    
    - name : enable libvirtd 
      service : name=libvirtd state=started enabled=yes

#    - name : enable openstack-nova-compute
#      service : name=openstack-nova-compute state=started enabled=yes
#
#    - name : enable neutron-openvswitch-agent
#      service : name=neutron-openvswitch-agent state=started enabled=yes
#   


    - name : dir nova owner
      file : path=/etc/nova state=directory owner=nova group=nova recurse=yes

    - name : dir neutron owner
      file : path=/etc/neutron state=directory owner=neutron group=neutron recurse=yes
