#- hosts: controller-server,net-server
- hosts: compute-server
#- hosts: install-server
  gather_facts: no
  tasks:

  - name: apt install openstack linzhbj
    apt : name=ntp state=latest

  - name : enable ntp
    service : name=ntp state=started enabled=yes
  


  - name: set timezone to America/New_York
    timezone:
      #name: Asia/Tokyo
      name: America/New_York
