#- hosts: controller-server,net-server
#- hosts: compute-server
#- hosts:  redpower6,ibms812lc1
#- hosts: install-server
#- hosts: accdnnservice
- hosts: ent-cp5-ppc64le
  gather_facts: no
  tasks:

  - name: install ntp
    apt : name=ntp state=latest

  - name : enable ntp
    service : name=ntp state=started enabled=yes
  


  - name: set timezone 
    timezone:
      #name: Asia/Tokyo
      #name: America/New_York
      name: Asia/Shanghai

