FROM ppc64le/ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y linux-libc-dev gcc openssh-server net-tools apt-utils vim python3

ADD . /bd_build
RUN cp /bd_build/bin/lsb_release /usr/bin/
#RUN mkdir /opt/RunOnce
#RUN cp -r /bd_build/bin/FlashGT /opt/RunOnce/
RUN apt-get install -y software-properties-common pciutils
#RUN /bd_build/install_flashgt.sh
RUN cd /bd_build/bin/FlashGT ; ./cflash_configure

RUN useradd -m -p '$1$super$uXdjVfWjBYtxOPjOXZb3k0' -s /bin/bash opuser
RUN usermod -aG sudo opuser
RUN sed -i 's/^SSHD_OPTS=$/SSHD_OPTS=-u0/' /etc/default/ssh
RUN sed -i 's/^exit 0$/service ssh start\nexit 0/' /etc/rc.local

RUN  /bd_build/update.sh

CMD ["/sbin/my_init"]
