- hosts: compute-server
  gather_facts: no
  tasks:
  - name: apt-get install openstack linzhbj
    apt : name=qemu,qemu-kvm,qemu-user,qemu-system-sparc,qemu-system-x86,qemu-system-misc,qemu-system-mips,qemu-system-arm,libvirt-bin,nova-compute,sysfsutils,python-novaclient,python-heatclient,neutron-plugin-ml2,neutron-plugin-openvswitch-agent,python-pip,git,vim,tree,lvm2,system-storage-manager,aufs-tools,cgroup-lite,git,git-man,liberror-perl,patch state=latest
