- hosts: compute-server
  remote_user : root
  gather_facts: no
  tasks:
  - name: install command
    apt : name=python-pip,python-dev,git,vim,tree,lvm2,system-storage-manager,patch state=latest

  - name: install libvirt
    apt : name=qemu,qemu-kvm,qemu-user,qemu-system-sparc,qemu-system-x86,qemu-system-misc,qemu-system-mips,qemu-system-arm,libvirt-bin,sysfsutils state=latest

  - name: install docker.io
    apt: name=docker.io,aufs-tools,cgroup-lite,git,git-man,liberror-perl  state=latest

  - name: apt-get install openstack
    apt : name=nova-compute,sysfsutils,python-novaclient,python-heatclient,neutron-plugin-ml2,neutron-plugin-openvswitch-agent state=latest

